# Generated by Django 4.2.7 on 2023-11-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('features', models.TextField(blank=True)),
                ('personalization', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('collection', models.CharField(choices=[('F', 'Folder'), ('O', 'Pen Organizer'), ('P', 'Planner')], max_length=1)),
            ],
        ),
    ]
