# Generated by Django 4.2.7 on 2023-11-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='PenOrganizer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('slots', models.IntegerField(default=0)),
            ],
            bases=('product.product',),
        ),
    ]
