# Generated by Django 4.2.7 on 2023-11-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_folder_penorganizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
    ]
