# Generated by Django 4.2.7 on 2023-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_amount_due_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift',
            field=models.BooleanField(default=False),
        ),
    ]
