# Generated by Django 4.2.7 on 2023-11-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recepient',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
