# Generated by Django 4.2.7 on 2023-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_due',
            field=models.FloatField(default=0, null=True),
        ),
    ]
